const MUTATION_TYPES = {
  GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',

  GET_DATA_REQUEST: 'GET_DATA_REQUEST',
  GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
  GET_DATA_FAILURE: 'GET_DATA_FAILURE',

  GET_COLUMNS_REQUEST: 'GET_COLUMNS_REQUEST',
  GET_COLUMNS_SUCCESS: 'GET_COLUMNS_SUCCESS',
  GET_COLUMNS_FAILURE: 'GET_COLUMNS_FAILURE'
}
export default MUTATION_TYPES
